### ISSUE TITLE
[CRITICAL BUG] Dont work on ubuntu 16.04 64-bit Mozilla 49.0

### ISSUE THREAD

**Issue by ArtemPopof** [BreezeGames/WGEclient#6]
> [Render constructor]: initializing webGL contextwUttils.js:8:9
> Error: WebGL: Disallowing antialiased backbuffers due to blacklisting.wRender.js:15:13
> Error: WebGL: Failed to create WebGL context: WebGL creation failed: Refused to create native OpenGL context because of blacklisting.
> Refused to create native OpenGL context because of blacklisting.wRender.js:15:13
> Error: [Render constructor]: webgl not supported!

**Comment by JorgenPo** [comment]
Please, download the last drivers for your video adapter. 
Best wishes, 
Popoff George
